title: "Casual blog"
description: "A blog where you can find and read about my interests."
url: "https://berserkermother.github.io"
baseurl: ""  
markdown: kramdown
highlighter: rouge
# theme: minima
minima:
  skin: dark
plugins:
- jekyll-remote-theme
remote_theme: jekyll/minima
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
author:
  name: "Kave Bahraman"
  email: "sadegh.b218@gmail.com"
